---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
ActivityData <- read.csv("./activity.csv")
```


## What is mean total number of steps taken per day?
```{r}
library(plyr) # Load plyr and ggplot2 package in case it is not already loaded
library(ggplot2)
sumAD <- ddply(ActivityData, 'date', summarize, sumsteps = sum(steps))
fr <- ggplot(sumAD, aes(sumsteps))
fr <- fr + geom_histogram(binwidth=2500,fill="darkred")
fr <- fr + scale_x_continuous(limits=c(0,20000))
fr <- fr + labs(y="Frequency",x="Number of steps", title="Frequency of number of steps taken each day in the period")
print(fr)

```

```{r}
meanAD <- as.integer(mean(sumAD$sumsteps,na.rm=TRUE)) # calculate the daily mean steps
medAD <- median(sumAD$sumsteps,na.rm=TRUE)
```
During the period the mean number of steps per day was `r meanAD` and the median was `r medAD`.

```{r}

```
## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
